### ISSUE TITLE
Datastore.php / Windows Dev AppEngine produces CGI/FastCGI issue

### ISSUE THREAD

**Issue by mf01** [google/google-api-php-client#640]
I'm using AppEngine under Windows for development. I've tried to create data in Datastore.

Unfortunately CGI/FastCGI will gone every time I call the demo script 
https://github.com/amygdala/appengine_php_datastore_example/blob/master/datastore_connect.php

![cgi_fastcgi_issue](https://cloud.githubusercontent.com/assets/1529283/9351156/5c24848a-4657-11e5-91e1-43a3e0631f98.png)

I've found that this line is producing the issue.

```
$service_dataset->commit($dataset_id, $req, []);
```

After looking to the Datastore.php from this lib I've replaced return value by a simple return.

``` php
  /**
   * Commit a transaction, optionally creating, deleting or modifying some
   * entities. (datasets.commit)
   *
   * @param string $datasetId Identifies the dataset.
   * @param Google_CommitRequest $postBody
   * @param array $optParams Optional parameters.
   * @return Google_Service_Datastore_CommitResponse
   */
  public function commit($datasetId, Google_Service_Datastore_CommitRequest $postBody, $optParams = array())
  {
    $params = array('datasetId' => $datasetId, 'postBody' => $postBody);
    $params = array_merge($params, $optParams);
    return;
    return $this->call('commit', array($params), "Google_Service_Datastore_CommitResponse");
  }
```

The issue was gone. As expected without data in the Google Datastore.

**Comment by Abbe98** [comment]
This also happens when running the [HelloAnalytics.php](https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/service-php).

**Comment by sjlangley** [comment]
The google php api client is not part of app engine, you should probably file this issue over on it's github project.

**Comment by marslangoog** [comment]
This is a known issue: https://code.google.com/p/googleappengine/issues/detail?id=12287

**Comment by bshaffer** [comment]
I would be interested to know if this happens with the newer version of the library, if anybody has time to test it.

**Comment by Abbe98** [comment]
I used the latest version this Saturday.

**Comment by mf01** [comment]
@bshaffer I've used the new lib and the issue was gone. Currently I've an authentication problem to storage but this shouldn't depend to this lib. I have to make more tests.

**Comment by bshaffer** [comment]
Great news @mf01!
I updated the `master` branch to use HTTP Streams instead of cURL on App Engine (see #715). I believe this has done the trick. @Abbe98 can you also confirm?

**Comment by Abbe98** [comment]
On the current master I got the error that the autoload has moved to `vendor/autoload.php`(seams weird as I'm not using composer and no `vendor/` exists)...

**Comment by bshaffer** [comment]
@Abbe98 composer is required in the new version, or you can download the release [here](https://github.com/google/google-api-php-client/releases) and the `vendor` directory is included.

**Comment by Abbe98** [comment]
Okey will install the master-branch from Composer then...

**Comment by Abbe98** [comment]
Getting `Fatal error: Class 'Google_Auth_AssertionCredentials' not found` from `master-dev`. 

So the crash is fixed and the **Hello Analytics API: PHP** is outdated.

**Comment by mf01** [comment]
@bshaffer I have another problem during update to the new version including composer.

This line will produce the error.
<pre>$service_dataset->commit($dataset_id, $req, []);</pre>

This is the issue.
<pre>
Notice: Object of class google\appengine\runtime\CurlLite could not be converted to int in [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php on line 109

Notice: Object of class google\appengine\runtime\CurlLite could not be converted to int in [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php on line 118

Fatal error: Uncaught exception 'google\appengine\runtime\CurlLiteOptionNotSupportedException' with message 'Option 20056 is not supported by this curl implementation.' in [path-to-gae]\appengine\runtime\CurlLite.php:487 Stack trace:
#0 [path-to-gae]\appengine\runtime\CurlLite.php(215): google\appengine\runtime\CurlLite->setOption(20056, NULL)
#1 [path-to-gae]\appengine\runtime\CurlLiteStub.php(1325): google\appengine\runtime\CurlLite->setOptionsArray(Array)
#2 [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php(130): curl_setopt_array(Object(google\appengine\runtime\CurlLite), Array)
#3 [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\guzzlehttp\rin in [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 51</pre>

Maybe I'm wrong or did forgotten something. But it's not working using Google App Engine (local) environment.

**Comment by bshaffer** [comment]
aha, this would be because the check `$client->isAppEngine()` does not return true for the dev appserver :anguished: 

You can [set the stream handler manually](https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L1037) in the meantime.

**Comment by mf01** [comment]
I'm sorry. The issue is still there.

So I've forced true return.
<pre>    // set StreamHandler on AppEngine by default
    if (true || $this->isAppEngine()) {
      $options['handler'] = new StreamHandler();
    }
</pre>

And I have a different message. 
<pre>Warning: Missing argument 1 for Monolog\Handler\StreamHandler::__construct(), called in [path-to-project]\lib\google-api-php-client-2.0.0-RC1\src\Google\Client.php on line 1042 and defined in [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 42

Notice: Undefined variable: stream in [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 45

Notice: Undefined variable: stream in [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 47

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'A stream must either be a resource or a string.' in [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:50 Stack trace:
#0 [path-to-project]\lib\google-api-php-client-2.0.0-RC1\src\Google\Client.php(1042): Monolog\Handler\StreamHandler->__construct()
#1 [path-to-project]\lib\google-api-php-client-2.0.0-RC1\src\Google\Client.php(1027): Google_Client->createDefaultHttpClient()
#2 [path-to-project]\lib\google-api-php-client-2.0.0-RC1\src\Google\Service\Resource.php(190): Google_Client->getHttpClient()
#3 [path-to-project]\lib\google-api-php-client-2.0.0-RC1\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 50</pre>

**Comment by gbittmann** [comment]
Have you tried adding a php.ini to your root that includes:

`extension = "php_curl.dll"`

I had a similar problem with gitkit + app engine php local and this solved the problem.

**Comment by tmatsuo** [comment]
Is this still an issue?
Also is everyone aware of the `google/cloud` library has `Datastore` package?
