### ISSUE TITLE
cURL error 60

### ISSUE THREAD

**Issue by amitsadana444** [google/google-api-php-client#843]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in D:\bin\xampp\htdocs\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 D:\bin\xampp\htdocs\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\bin\xampp\htdocs\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\bin\xampp\htdocs\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleH in D:\bin\xampp\htdocs\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

What is this problem?
How can I solve this?
I checked a lot of links related with this, but no result.
Please help me all.
Thanks for your time.

**Comment by bshaffer** [comment]
Hmm, at a glance this seems like an underlying curl problem, or even an underlying Guzzle problem, and not an issue with this library.

**Comment by bshaffer** [comment]
This [stack overflow](http://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate) provides several ways to work around this problem.

**Comment by sarasad** [comment]
hii , 
i'm having the same problem , how did u slove it please 
help

**Comment by bshaffer** [comment]
* Save the following to `cacert.pem`: https://curl.haxx.se/ca/cacert.pem

* put it here:

    > C:\xampp\php\extras\ssl\cacert.pem

* in your php.ini put this line in this section:
    ```
    ;;;;;;;;;;;;;;;;;;;;
    ; php.ini Options  ;
    ;;;;;;;;;;;;;;;;;;;;

    curl.cainfo = "C:\xampp\php\extras\ssl\cacert.pem"
    ```
* restart your webserver/apache

**Comment by sarasad** [comment]
Thank youu , 
i did that but still not working :(

**Comment by bshaffer** [comment]
@sarasad it's possible you added it to the wrong `php.ini` or did not properly restart your web server. Add a file such as this and ensure the `curl.cainfo` value is as expected:

```html+php
<?php
// somefile.php

phpinfo();
```

If that doesn't work, try seeing the [guzzle documentation](http://docs.guzzlephp.org/en/latest/request-options.html#verify) on how to provide your own cert file directly (https://github.com/guzzle/guzzle/issues/394). For this library, it will look something liek this:

```php
$http = new GuzzleHttp\Client([
    'verify' => '/path/to/cert.pem'
];
$google = new Google_Client;
$google->setHttpClient($http);
```

**Comment by sarasad** [comment]
Thank you so much for replying 
but still same problem :( 
this is the msg i gt exactly  : 
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\api-samples-master\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:188 Stack trace: #0 C:\xampp\htdocs\api-samples-master\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(151): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\api-samples-master\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(104): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\api-samples-master\php\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\ in C:\xampp\htdocs\api-samples-master\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 188

**Comment by aingelc12ell** [comment]
Looks like this problem occurs from a local location (like you workstation). 

Had the same problem.
However, when I uploaded and ran it on my webserver, it works.

Same thing, I'd like to know how to resolve it, running from my machine.

**Comment by cylosh** [comment]
put 'verify' => false

**Comment by df257** [comment]
me too.... curl.cainfo = "xxx\cacert.pem" it's not worke, php.ini is in apache/bin

**Comment by ATXcoder** [comment]
I have WAMP running on my Windows box and was able to solve this issue following @bshaffer instructions but with some minor adjustments. One thing to keep in mind at least if you are running WAMP (not sure if the same applies to LAMP) is that WAMP may be using two different versions of PHP (for me it was version 5 & 7). It uses version 5 for the command line and version 7 for web apps. Here's how I fixed mine:

1. Placing the cacert.perm from [https://curl.haxx.se/ca/cacert.pem](https://curl.haxx.se/ca/cacert.pem) in the correct folder. In my case it was "C:\wamp\bin\php\php5.6.19\extras\ssl". 

2. Modify php.ini, found in folder "C:\Wamp\bin\php\php5.6.19".  Find the following section
`;;;;;;;;;;;;;;;;;;;;
; php.ini Options  ;
;;;;;;;;;;;;;;;;;;;;`
and add the following line to that section (modify the folder path to match where you placed the cacert.pem file): 
**curl.cainfo = "C:\wamp\bin\php\php5.6.19\extras\ssl\cacert.pem"** 

3. Save the file

4. Restart PHP (I just click in the WAMP icon in the system tray and click on "Restart All Services"

You should then be able to run the Google Calendar API Quickstart example.

**Comment by Stankim** [comment]
Thank you  bshaffer. Worked for me. Using xampp in windows

**Comment by Hujjat** [comment]
@ATXcoder did not work on wamp. I still get the same errors.

**Comment by basitmakine** [comment]
@bshaffer Adding cacert.pem did the trick for me on XAMPP Windows. Thanks!

**Comment by Nnutthowze** [comment]
@bshaffer I'm use AMPPS, it helped me as well, thanks for the solution!

**Comment by sstankov** [comment]
See how this guy fixed it: https://translate.google.bg/translate?hl=en&sl=ja&u=https://qiita.com/kd9951/items/c5d2add24afe861ebe2e&prev=search

**Comment by abdul202** [comment]
i have another apprrocahe it works for me
open vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php

and change thsi
```
$conf[CURLOPT_SSL_VERIFYHOST] = 2;
                $conf[CURLOPT_SSL_VERIFYPEER] = true;

```to this
```
$conf[CURLOPT_SSL_VERIFYHOST] = 0;
                $conf[CURLOPT_SSL_VERIFYPEER] = FALSE;
```
it's a temporary solution if you upated this file the changes will lost

**Comment by Mohd-Hasan** [comment]
thanks @abdul202 it is working

**Comment by brsvrgn** [comment]
thanks @abdul202 also worked for me.

**Comment by TomixChiu** [comment]
> * Save the following to `cacert.pem`: https://curl.haxx.se/ca/cacert.pem
> * put it here:
>   > C:\xampp\php\extras\ssl\cacert.pem
> * in your php.ini put this line in this section:
>   ```
>   ;;;;;;;;;;;;;;;;;;;;
>   ; php.ini Options  ;
>   ;;;;;;;;;;;;;;;;;;;;
>   
>   curl.cainfo = "C:\xampp\php\extras\ssl\cacert.pem"
>   ```
> * restart your webserver/apache

I follw your steps, and solve this problem, thanks!

**Comment by beppe9000** [comment]
is there a way to temporarily disable ssl checking like a static field somewhere?

**Comment by jdpedrie** [comment]
@beppe9000,

You can provide your own HTTP client with SSL verification disabled. Of course, you should **never** use this in production.

```php
$client = new Google_Client();
$guzzle = new GuzzleHttp\Client([
    'verify' => false
]);
$client->setHttpClient($guzzle);
```

**Comment by asp1egui** [comment]
Since these tricks didn't work on my machine .  What i did was just adding the ca file path in the  variable conf of the getDefaultConf method of the CurlFactory file like this. 
`CURLOPT_CAINFO => 'C:\xampp\php\extras\ssl\cacert.pem', `

**Comment by npapratovic** [comment]
@ATXcoder thanks for tip about different versions of php running on local machine. I have 4 versions, and I just applied your solution to all 4 version, and error is gone. Thanks

**Comment by Asad0313** [comment]
Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404
mobixpress.com
Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.3.6

i'm getting this error 
my site will reach on facebook login but when its redirect to my localhost which name is mobixpress.com it will through this error which i've mention above.
i know its a error of https or ssl 
but i dont know how to resolve it
any one can please help me

**Comment by attuarrahman** [comment]
> i have another apprrocahe it works for me
> open vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php
> 
> and change thsi
> 
> ```
> $conf[CURLOPT_SSL_VERIFYHOST] = 2;
>                 $conf[CURLOPT_SSL_VERIFYPEER] = true;
> ```
> 
> to this
> 
> ```
>               $conf[CURLOPT_SSL_VERIFYHOST] = 0;
>                 $conf[CURLOPT_SSL_VERIFYPEER] = FALSE;
> ```
> 
> it's a temporary solution if you upated this file the changes will lost

thank you so much its working fine.

**Comment by jdpedrie** [comment]
@attuarrahman while I'm glad that is helping, it is not a good idea to make manual changes to external libraries. When you run `composer update` those changes will be overwritten. I [shared above](https://github.com/googleapis/google-api-php-client/issues/843#issuecomment-482706351) how to configure your client without changes to external code.

That said, if you are experiencing this issue on your production server, I *strongly* advise that you work with whoever manages your hosting to address the issue. It is very dangerous to disable SSL verification in production. If you are doing this in development, I'd still suggest working to address the underlying problem, though it's less urgent so long as you are careful not to let that change make it to production.
